# Generated by Django 3.2.5 on 2021-08-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
